-- MySQL Script generated by MySQL Workbench
-- lun 03 feb 2020 01:25:53 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ROL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ROL` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ROL` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`USER` ;

CREATE TABLE IF NOT EXISTS `mydb`.`USER` (
  `userId` VARCHAR(45) NOT NULL,
  `DPI` VARCHAR(45) NOT NULL,
  `codePersonal` VARCHAR(45) NULL,
  `carnet` VARCHAR(45) NULL,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `password` VARCHAR(400) NOT NULL,
  `ROL_id` INT NOT NULL,
  PRIMARY KEY (`userId`),
  CONSTRAINT `fk_USER_ROL1`
    FOREIGN KEY (`ROL_id`)
    REFERENCES `mydb`.`ROL` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `DPI_UNIQUE` ON `mydb`.`USER` (`DPI` ASC) VISIBLE;

CREATE INDEX `fk_USER_ROL1_idx` ON `mydb`.`USER` (`ROL_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`CAREER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CAREER` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CAREER` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USER_CAREER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`USER_CAREER` ;

CREATE TABLE IF NOT EXISTS `mydb`.`USER_CAREER` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `USER_id` INT NOT NULL,
  `CAREER_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_USER_CAREER_USER`
    FOREIGN KEY (`USER_id`)
    REFERENCES `mydb`.`USER` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_CAREER_CAREER1`
    FOREIGN KEY (`CAREER_id`)
    REFERENCES `mydb`.`CAREER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USER_CAREER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`USER_CAREER` ;

CREATE TABLE IF NOT EXISTS `mydb`.`USER_CAREER` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `USER_id` INT NOT NULL,
  `CAREER_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_USER_CAREER_USER`
    FOREIGN KEY (`USER_id`)
    REFERENCES `mydb`.`USER` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_CAREER_CAREER1`
    FOREIGN KEY (`CAREER_id`)
    REFERENCES `mydb`.`CAREER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_USER_CAREER_USER_idx` ON `mydb`.`USER_CAREER` (`USER_id` ASC) VISIBLE;

CREATE INDEX `fk_USER_CAREER_CAREER1_idx` ON `mydb`.`USER_CAREER` (`CAREER_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`PREPROJECT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PREPROJECT` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PREPROJECT` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`REQUERIMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`REQUERIMENT` ;

CREATE TABLE IF NOT EXISTS `mydb`.`REQUERIMENT` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `writtenRequest` MEDIUMBLOB NOT NULL,
  `inscriptionConstancy` MEDIUMBLOB NOT NULL,
  `pensumClosure` MEDIUMBLOB NOT NULL,
  `propedeuticConstancy` MEDIUMBLOB NOT NULL,
  `EPSpreproject` MEDIUMBLOB NOT NULL,
  `AEIOsettlement` MEDIUMBLOB NULL,
  `PREPROJECT_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_REQUERIMENT_PREPROJECT1`
    FOREIGN KEY (`PREPROJECT_id`)
    REFERENCES `mydb`.`PREPROJECT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_REQUERIMENT_PREPROJECT1_idx` ON `mydb`.`REQUERIMENT` (`PREPROJECT_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`DOCUMENT_INITIAL_EPS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DOCUMENT_INITIAL_EPS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DOCUMENT_INITIAL_EPS` (
  `id` INT NOT NULL,
  `approvalAct` MEDIUMBLOB NULL,
  `adviserProposal` MEDIUMBLOB NULL,
  `reviewerProposal` MEDIUMBLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`APPOINTMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`APPOINTMENT` ;

CREATE TABLE IF NOT EXISTS `mydb`.`APPOINTMENT` (
  `id` INT NOT NULL,
  `USER_adviser` VARCHAR(45) NOT NULL,
  `USER_reviewer` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_APPOINTMENT_USER1`
    FOREIGN KEY (`USER_adviser`)
    REFERENCES `mydb`.`USER` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_APPOINTMENT_USER2`
    FOREIGN KEY (`USER_reviewer`)
    REFERENCES `mydb`.`USER` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_APPOINTMENT_USER1_idx` ON `mydb`.`APPOINTMENT` (`USER_adviser` ASC) VISIBLE;

CREATE INDEX `fk_APPOINTMENT_USER2_idx` ON `mydb`.`APPOINTMENT` (`USER_reviewer` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`DELIVER__EPS_COMPLETION_DOCUMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DELIVER__EPS_COMPLETION_DOCUMENT` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DELIVER__EPS_COMPLETION_DOCUMENT` (
  `id` INT NOT NULL,
  `deliveryFinalReport` TINYINT NOT NULL,
  `counterpartSettlement` MEDIUMBLOB NOT NULL,
  `reviewerLetter` MEDIUMBLOB NOT NULL,
  `adviserLetter` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROCESS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PROCESS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PROCESS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `USER_CAREER_id` INT NOT NULL,
  `state` TINYINT NOT NULL,
  `REQUERIMENT_id` INT NOT NULL,
  `approvedCareerCoordinator` TINYINT NOT NULL,
  `documentApprovedCareerCoordinator` MEDIUMBLOB NULL,
  `DocumentsToEPSCareerSupervisor` TINYINT NOT NULL,
  `DocumentsToEPSCommission` TINYINT NOT NULL,
  `PreProjectToEPSCommission` TINYINT NOT NULL,
  `approvalEPSCommission` TINYINT NULL,
  `DOCUMENT_INITIAL_EPS_id` INT NULL,
  `APPOINTMENT_id` INT NULL,
  `approvedEPSDevelopment` TINYINT NOT NULL,
  `DELIVER__EPS_COMPLETION_DOCUMENT_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_PROCESS_USER_CAREER1`
    FOREIGN KEY (`USER_CAREER_id`)
    REFERENCES `mydb`.`USER_CAREER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROCESS_REQUERIMENT1`
    FOREIGN KEY (`REQUERIMENT_id`)
    REFERENCES `mydb`.`REQUERIMENT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROCESS_DOCUMENT_INITIAL_EPS1`
    FOREIGN KEY (`DOCUMENT_INITIAL_EPS_id`)
    REFERENCES `mydb`.`DOCUMENT_INITIAL_EPS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROCESS_APPOINTMENT1`
    FOREIGN KEY (`APPOINTMENT_id`)
    REFERENCES `mydb`.`APPOINTMENT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROCESS_DELIVER__EPS_COMPLETION_DOCUMENT1`
    FOREIGN KEY (`DELIVER__EPS_COMPLETION_DOCUMENT_id`)
    REFERENCES `mydb`.`DELIVER__EPS_COMPLETION_DOCUMENT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PROCESS_USER_CAREER1_idx` ON `mydb`.`PROCESS` (`USER_CAREER_id` ASC) VISIBLE;

CREATE INDEX `fk_PROCESS_REQUERIMENT1_idx` ON `mydb`.`PROCESS` (`REQUERIMENT_id` ASC) VISIBLE;

CREATE INDEX `fk_PROCESS_DOCUMENT_INITIAL_EPS1_idx` ON `mydb`.`PROCESS` (`DOCUMENT_INITIAL_EPS_id` ASC) VISIBLE;

CREATE INDEX `fk_PROCESS_APPOINTMENT1_idx` ON `mydb`.`PROCESS` (`APPOINTMENT_id` ASC) VISIBLE;

CREATE INDEX `fk_PROCESS_DELIVER__EPS_COMPLETION_DOCUMENT1_idx` ON `mydb`.`PROCESS` (`DELIVER__EPS_COMPLETION_DOCUMENT_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`PROPERTY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PROPERTY` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PROPERTY` (
  `id` INT NOT NULL,
  `MAXIMUM_SUPERVISOR_WORKLOAD` INT NOT NULL,
  `VALIDATION_PERCENTAGE_EXTENSION` INT NOT NULL,
  `REVIEW_TIME_DAYS` INT NOT NULL,
  `TIME_OF_PROCESS_WITHOUT_MOVEMENT` INT NOT NULL,
  `DEADLINE_TO_SUBMIT_DOCUMENTS` DATE NOT NULL,
  `MINIMUN_EXECUTION_MONTHS` INT NOT NULL,
  `MAXIMUN_EXECUTION_MONTHS` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BINNACLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`BINNACLE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`BINNACLE` (
  `id` INT NOT NULL,
  `DOCUMENT_INITIAL_EPS_id` INT NOT NULL,
  `activity` VARCHAR(45) NOT NULL,
  `dateTime` DATETIME NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `annotation` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_BINNACLE_DOCUMENT_INITIAL_EPS1`
    FOREIGN KEY (`DOCUMENT_INITIAL_EPS_id`)
    REFERENCES `mydb`.`DOCUMENT_INITIAL_EPS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_BINNACLE_DOCUMENT_INITIAL_EPS1_idx` ON `mydb`.`BINNACLE` (`DOCUMENT_INITIAL_EPS_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`EXTRA_FILE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EXTRA_FILE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EXTRA_FILE` (
  `id` INT NOT NULL,
  `file` MEDIUMBLOB NOT NULL,
  `BINNACLE_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_EXTRA_FILE_BINNACLE1`
    FOREIGN KEY (`BINNACLE_id`)
    REFERENCES `mydb`.`BINNACLE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_EXTRA_FILE_BINNACLE1_idx` ON `mydb`.`EXTRA_FILE` (`BINNACLE_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`SUPERVISION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SUPERVISION` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SUPERVISION` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `annotation` VARCHAR(200) NULL,
  `PROCESS_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_SUPERVISION_PROCESS1`
    FOREIGN KEY (`PROCESS_id`)
    REFERENCES `mydb`.`PROCESS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_SUPERVISION_PROCESS1_idx` ON `mydb`.`SUPERVISION` (`PROCESS_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`DOCUMENT_FINAL_EPS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DOCUMENT_FINAL_EPS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DOCUMENT_FINAL_EPS` (
  `id` INT NOT NULL,
  `epsCareerSupervisorOpinion` VARCHAR(45) NOT NULL,
  `certificateConclusionByEPSCoordinator` MEDIUMBLOB NOT NULL,
  `finalReport` MEDIUMBLOB NOT NULL,
  `transcriptionCertificateConclusionEPS` MEDIUMBLOB NOT NULL,
  `transferToCoordinatingSecretary` TINYINT NOT NULL,
  `PROCESS_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_DOCUMENT_FINAL_EPS_PROCESS1`
    FOREIGN KEY (`PROCESS_id`)
    REFERENCES `mydb`.`PROCESS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_DOCUMENT_FINAL_EPS_PROCESS1_idx` ON `mydb`.`DOCUMENT_FINAL_EPS` (`PROCESS_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`TITLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TITLE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TITLE` (
  `id` INT NOT NULL,
  `text` VARCHAR(200) NULL,
  `TITLE_id` INT NOT NULL,
  `PREPROJECT_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_TITULO_TITULO1`
    FOREIGN KEY (`TITLE_id`)
    REFERENCES `mydb`.`TITLE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TITULO_PREPROJECT1`
    FOREIGN KEY (`PREPROJECT_id`)
    REFERENCES `mydb`.`PREPROJECT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TITULO_TITULO1_idx` ON `mydb`.`TITLE` (`TITLE_id` ASC) VISIBLE;

CREATE INDEX `fk_TITULO_PREPROJECT1_idx` ON `mydb`.`TITLE` (`PREPROJECT_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`TEXTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TEXTO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TEXTO` (
  `id` INT NOT NULL,
  `text` BLOB NOT NULL,
  `TITLE_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_TEXTO_TITULO1`
    FOREIGN KEY (`TITLE_id`)
    REFERENCES `mydb`.`TITLE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TEXTO_TITULO1_idx` ON `mydb`.`TEXTO` (`TITLE_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

