
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package ejemplo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMA = 10;
  public static final int MENOS = 3;
  public static final int POR = 4;
  public static final int EOF = 0;
  public static final int MAS = 2;
  public static final int NUMERO = 12;
  public static final int DIV = 5;
  public static final int IGUAL = 6;
  public static final int error = 1;
  public static final int LETRAZ = 9;
  public static final int PUNTOYCOMA = 11;
  public static final int LETRAY = 8;
  public static final int LETRAX = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "IGUAL",
  "LETRAX",
  "LETRAY",
  "LETRAZ",
  "COMA",
  "PUNTOYCOMA",
  "NUMERO"
  };
}

